### ISSUE TITLE
Infer data type from dataset

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#196]
Infer data_type (func or anat or both) from dataset rather than use command line parameter.

**Comment by oesteban** [comment]
The data_type is actually inferred from the dataset, the --data_type option is there to restrict the analysis to one of those if the user does not want to process all. In practice, if you have a dataset with both anatomical and functional data, you'd use --data_type to run only the anatomical or only the functional.

However, this issue here comes from a bug in the group level. It breaks in several use cases. This issue will be closed when those bugs are fixed.
