### ISSUE TITLE
Finish up spikes detection on fMRI

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#216]

**Comment by chrisfilo** [comment]
I've been playing with using heatmaps to show which slices have outliers. It's great for multiband spikes (because you see that there are as many slices with outliers as the multi band factor):
![image](https://cloud.githubusercontent.com/assets/238759/19422525/b1dd1a38-93ca-11e6-98cb-d7b69b29dca0.png)

At the same time this method might make single band spikes hard to spot (since you can miss one red dot):
![image](https://cloud.githubusercontent.com/assets/238759/19422534/d5042ccc-93ca-11e6-96e4-4b3c3c9fdf5e.png)

**Comment by oesteban** [comment]
That looks great!. We could enable these plots only for multiband data.

In this issue I was referring to high frequency spikes, using the FFT.
