### ISSUE TITLE
FD count distribution unreadable

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#313]
![image](https://cloud.githubusercontent.com/assets/238759/20764756/8208fad8-b6e4-11e6-898d-add8f70ccee3.png)

**Comment by oesteban** [comment]
This happens in two scenarios:

1. When all samples have value 0
2. When there is at least one outlier with a value very off the distribution.

For 1) we can center the graph, but strictly speaking _there is no bug here_. For 2) since we removed clipping the range to better fit the distribution this would happen. We could add that clipping only for these three IQMs. WDYT @chrisfilo ?

**Comment by chrisfilo** [comment]
Note to self - write down the provenance of data when reporting bugs.

I think this must've been case 1 - all zero value - since I don't see any outliers. I think we can close it. Sorry for the confusion!

**Comment by oesteban** [comment]
Yes - but case 2 is still there, so it was worth addressing.
