### ISSUE TITLE
how to investigate the failure?

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/mriqc#317]
crashed with "Workflow did not execute cleanly":
http://www.onerussian.com/tmp/gkrellShoot_12-02-16_112644.png
is the a nipype command to help decypher what is stored in those pickles?

**Comment by chrisfilo** [comment]
http://nipype.readthedocs.io/en/latest/users/debug.html

On Fri, Dec 2, 2016 at 8:42 AM, Yaroslav Halchenko <notifications@github.com

**Comment by oesteban** [comment]
As I can read in the screenshot it is failing in the SpatialNormalization node. That is the wrapper of antsRegistration. It seems to me that either a) the default settings in mriqc are not working for you; or b) the input images are not OK.

I would be very interested on a) in order to look for better parameters that work for you. I would be concerned about b), because I fixed yesterday a buggy data casting which in some cases reduced the range of the variables (basically making the images useless).

In those pickles you will find the inputs (so you will be able to check the ```moving_image``` and see if this faulty casting affected the results). Otherwise it is likely that you find the infamous ```itk::MattesMutualInformation <...> too many samples map outside the moving image``` from ants.

**Comment by oesteban** [comment]
@yarikoptic can we close this issue? Do you have any suggestions from this experience to improve mriqc's documentation?

**Comment by yarikoptic** [comment]
yeah -- let's close (for now or forever! ;) )
