### ISSUE TITLE
Add resolution, FOV and number of timepoints to metadata

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#335]

**Comment by oesteban** [comment]
What should be exactly reported for FoV? Is it in the sidecar json?

**Comment by chrisfilo** [comment]
It's a fancy name for the number of voxels along each axis. Can be read
from the nifti header.

**Comment by oesteban** [comment]
- For the anatomical, we have the following fields as IQMs: `size_[x,y,z]` and `spacing_[x,y,z]`
- For the functional, we have `size_[x,y,z,t]` and `spacing_[x,y,z,t]`

Should we move them from the regular IQMs section to the metadata dictionary? If so, please reopen this issue. Otherwise we can say this is already implemented.
