### ISSUE TITLE
Add suggested memory settings when using Docker

### ISSUE THREAD

**Issue by ritcheym** [poldracklab/mriqc#388]
Hi, thanks for your work on this app- it looks terrific and I'm looking forward to using it. I tried to run it through Docker on a small set of demo data, and the process has been killed each of the 3 times I've tried. I've attached the full set of terminal output. I'm running it locally on an iMac with 16GB RAM.

It appears to generate a crash file on antsApplyTransforms:
```
Running: antsApplyTransforms --default-value 0 --dimensionality 3 --input /usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/1mm_headmask.nii.gz --interpolation NearestNeighbor --output 1mm_headmask_trans.nii.gz --reference-image /scratch/work/workflow_enumerator/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-s03..anat..sub-s03_T1w.nii/binarize/sub-s03_T1w_conformed_corrected_calc_thresh.nii.gz --transform [ /scratch/work/workflow_enumerator/anatMRIQC/_in_file_..data..sub-s03..anat..sub-s03_T1w.nii/SpatialNormalization/ants_t1_to_mni0GenericAffine.mat, 1 ]
170217-03:01:02,925 interface INFO:
	 stdout 2017-02-17T03:01:02.925178:Using double precision for computations.
170217-03:01:02,925 interface INFO:
	 stdout 2017-02-17T03:01:02.925178:Input scalar image: /usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/1mm_headmask.nii.gz
170217-03:01:06,335 workflow ERROR:
	 [u'Node invert_xfm.a2 failed to run on host e255a528dc8e.']
170217-03:01:06,559 workflow INFO:
	 Saving crash info to /scratch/out/logs/crash-20170217-030106-root-invert_xfm.a2-77282183-ba20-4960-90af-751e458f65d2.pklz
```
And then it just stops running after about 5 hours. Nothing is saved to the `out` directory except the crash files in the `logs` folder.

```
Executing node compute_tsnr.a05 in dir: /scratch/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-s01..func..sub-s01_task-TASK_run-5_bold.nii.gz/compute_tsnr
170217-04:03:43,152 workflow INFO:
	 Executing node SpikesFinderFFT.a02 in dir: /scratch/work/workflow_enumerator/funcMRIQC/ComputeIQMs/_in_file_..data..sub-s01..func..sub-s01_task-TASK_run-2_bold.nii.gz/SpikesFinderFFT
/usr/bin/run_mriqc: line 5:    17 Killed                  mriqc $@
```
Let me know if any other information would be helpful. 
[mriqc_output.txt](https://github.com/poldracklab/mriqc/files/785378/mriqc_output.txt)

**Comment by chrisfilo** [comment]
Could you check on Docker settings how much of the 16gb was available to
Docker?

On Feb 18, 2017 2:39 PM, "Maureen Ritchey" <notifications@github.com> wrote:

Hi, thanks for your work on this app- it looks terrific and I'm looking
forward to using it. I tried to run it through Docker on a small set of
demo data, and the process has been killed each of the 3 times I've tried.
I've attached the full set of terminal output. I'm running it locally on an
iMac with 16GB RAM.

It appears to generate a crash file on antsApplyTransforms:

Running: antsApplyTransforms --default-value 0 --dimensionality 3
--input /usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/1mm_headmask.nii.gz
--interpolation NearestNeighbor --output 1mm_headmask_trans.nii.gz
--reference-image
/scratch/work/workflow_enumerator/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-s03..anat..sub-s03_T1w.nii/binarize/sub-s03_T1w_conformed_corrected_calc_thresh.nii.gz
--transform [ /scratch/work/workflow_enumerator/anatMRIQC/_in_file_..data..sub-s03..anat..sub-s03_T1w.nii/SpatialNormalization/ants_t1_to_mni0GenericAffine.mat,
1 ]
170217-03:01:02,925 interface INFO:
	 stdout 2017-02-17T03:01:02.925178:Using double precision for computations.
170217-03:01:02,925 interface INFO:
	 stdout 2017-02-17T03:01:02.925178:Input scalar image:
/usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/1mm_headmask.nii.gz
170217-03:01:06,335 workflow ERROR:
	 [u'Node invert_xfm.a2 failed to run on host e255a528dc8e.']
170217-03:01:06,559 workflow INFO:
	 Saving crash info to
/scratch/out/logs/crash-20170217-030106-root-invert_xfm.a2-77282183-ba20-4960-90af-751e458f65d2.pklz

And then it just stops running after about 5 hours. Nothing is saved to the
out directory except the crash files in the logs folder.

Executing node compute_tsnr.a05 in dir:
/scratch/work/workflow_enumerator/funcMRIQC/_in_file_..data..sub-s01..func..sub-s01_task-TASK_run-5_bold.nii.gz/compute_tsnr
170217-04:03:43,152 workflow INFO:
	 Executing node SpikesFinderFFT.a02 in dir:
/scratch/work/workflow_enumerator/funcMRIQC/ComputeIQMs/_in_file_..data..sub-s01..func..sub-s01_task-TASK_run-2_bold.nii.gz/SpikesFinderFFT
/usr/bin/run_mriqc: line 5:    17 Killed                  mriqc $@

Let me know if any other information would be helpful.
mriqc_output.txt
<https://github.com/poldracklab/mriqc/files/785378/mriqc_output.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/mriqc/issues/388>, or mute the thread

**Comment by ritcheym** [comment]
Oh hey, that was an easy fix! It appears that 2GB is the default memory setting on a fresh installation of Docker. Once I adjusted that in the settings, everything ran as expected. Thanks! It might be helpful to add that suggestion to the docs for other new Docker users.

**Comment by oesteban** [comment]
Will add this issue to the Docker user guide soon! Thanks :)
