### ISSUE TITLE
Bug on derivative dir specification for Group level analysis

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#392]
When running group-level analysis, after having ran participant level analyses independently, the derivatives directory used to search for json iqm files is the bids_dir rather than the out/derivatives folder.

**Comment by chrisfilo** [comment]
Could you share the exact command lines you used?

**Comment by oesteban** [comment]
This was intended to be a feature.

If you use the ```--participant_label``` in the ```participant``` level, the ```group``` level is not run, and the json files with the IQMs is written to ```<out-dir>/derivatives```.

Since the ```group``` level is just another bids-apps compatible command, now the input data for that level is in ```<out-dir>/derivatives```, and should follow the bids-derivatives spec.

Therefore:
```
mriqc <out-dir-of-participant-level>/derivatives out/ group
```
will generate the summary CSV file in ```out/``` and the reports in the ```out/reports``` folder.

**Comment by chrisfilo** [comment]
I also find it confusing and preferred the previous behavior where the input BIDS folder was always the same independently of the analysis level. This is what we had in mind with the BIDS Apps paper. Citing from it:

```
./my_pipeline /data/my_dataset /scratch/outputs participant --participant_label 01
./my_pipeline /data/my_dataset /scratch/outputs participant --participant_label 02
./my_pipeline /data/my_dataset /scratch/outputs participant --participant_label 03
./my_pipeline /data/my_dataset /scratch/outputs group
```
