### ISSUE TITLE
Improve performance of ComputeQI2

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#397]
I've noticed that the following nodes are unusually slow:

- ComputeQI2
- ~~SpikesFinder~~ (#509)
- ~~SpikesFinderFFT~~ (#509)

**Comment by chrisfilo** [comment]
Things I found out:

 - The output of SpikesFinder is not used anywhere
 - `median_filter`  in SpikesFinderFFT is making it run twice as long as without it
 - SpikesFinderFFT saves float64 files

**Comment by oesteban** [comment]
This will change QI2, and now it is the most predictive feature. Pushing to 0.9.8.

Changes I intend to apply:
- Deviate from Mortamet et al. 2009: use KDE (kernel density estimation) instead of histogram. This will improve substantially two issues:
  - The GoF (goodness-of-fit) can be calculated in more dense linear space (expected lower average errors for distributions well fitted).
  - The location of the threshold for the GoF calculation will be more robust.
- Model fitting: currently we are fitting the chi squared to the data in the background themselves. Mortamet et al. fit the PDF (that now will be smoother with KDE). That will be significantly faster.
