### ISSUE TITLE
[Idea] Match workdir folders mriqc/fmriprep and check if file exists to avoid recomputing

### ISSUE THREAD

**Issue by erramuzpe** [poldracklab/mriqc#440]
Hi @oesteban @chrisfilo ,

first of all, thanks for both packages :) . This issue could have been opened also in **fmriprep** repo... So I've testing them (with docker and sharing same workdir) in the last days and I realized that part of the workflows are the same. I don't really know if you want to keep both packages independent and this is more "user issue", but let me explain this. For instance: 

This file in **mriqc**...

`/home/asier/(...)/scratch/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-001..anat..sub-001_T1w.nii.gz/sstrip_orig_vol/sub-001_T1w_conformed_calc.nii.gz`

...and this one in **fmriprep**...

`/home/asier/(...)/scratch/workflow_enumerator/sub-001/t1w_preprocessing/AFNISkullStripWorkflow/sstrip_orig_vol/sub-001_T1w_calc.nii.gz`

... are the same. 

This T1-example is not computationally expensive, but _antsRegistration_ takes a long time (in case it's the same in **mriqc** and **fmriprep**). 

So, my question is; what are the implications of trying to match folders/files and check if it's already computed before actually running the job? In case, what would be needed; a protocol for organizing intermediate files and a file checker? :thinking:

**Comment by chrisfilo** [comment]
In principle this could be done via `derivatives` folder organized according to [BIDS Derivatives](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit) (work dirs are ephemeral by definition). However, the two projects differ in their processing pipelines for a reason. MRIQC tries to avoid any data cleaning and tends to use faster rather than time consuming and more accurate methods. FMRIPREP is optimized to produce preprocessed and cleaned outputs to the highest possible quality. Those two goals are sometimes at odds.

**Comment by oesteban** [comment]
I'm moving this to FMRIPREP, as more and more people are suggesting they'd like to have QC metrics amongst their fmriprep outputs.
