### ISSUE TITLE
Update documentation: SNR & number of timepoints

### ISSUE THREAD

**Issue by stjep** [poldracklab/mriqc#622]
What does *n* refer to in the [SNR calculation](http://mriqc.readthedocs.io/en/latest/iqms/t1w.html#mriqc.qc.anatomical.snr)? I noticed that the BOLD group report lumps together runs with different timepoints, and I'm wondering if *n* refers to the number of timepoints, as is common in some calculations.

**Comment by oesteban** [comment]
Hi @stjep it is the number of samples within the mask. I'll update the documentation: those docstrings are so outdated. Sorry about that.

**Comment by stjep** [comment]
@oesteban, no worries. I was curious because the group plots combine short tasks with longer tasks. Could you end up with a scenario where the SNR differs between two tasks not because of the actual SNR but because of _n_?

**Comment by oesteban** [comment]
That *n* is just a correction factor for the bias of the standard deviation estimator. If you are working with timeseries, they you'll be interested on the tSNR - http://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-tsnr

However, our understanding of tSNR is especially limited. We haven't had enough time to characterize the different quality metrics, and tSNR is one of those with the most space to search in terms of how the length of the time series affects, the spatial distribution of the measure, etc.

So, concisely, the answer is no, we don't know the implications of the length of the task on the tSNR measures.

**Comment by chrisfilo** [comment]
In theory I don't see how the length of scan could systematically bias tSNR. It could be the case that due to thermal noise the images get noisier with the length of the scan, but this is something you would like to see.

BTW asking this question (is there a relationship between number of timepoints and tSNR) would be very easy with the data collected in the MRIQC Web API: https://gist.github.com/chrisfilo/eccdb8b98f8e74d24a3395a49fbadf03
