### ISSUE TITLE
questions about MRIQC (use output of other pipeline; reports for other MRI image; test example)

### ISSUE THREAD

**Issue by s165838** [poldracklab/mriqc#791]
Hi all,
 
I am a beginner and have several questions about MRIQC. 1) How to run MRIQC using the outputs from another pipeline that didn’t use the MRIQC workflow? 2) Can MRIQC generate qualitative reports for other MRI contrasts (besides anatomical and functional), such as diffusion MRI, QSM MRI? 3) Where can I get an test example of MRIQC. I appreciate very much for your time.

Best,

Zhiguo

**Comment by oesteban** [comment]
> 1) How to run MRIQC using the outputs from another pipeline that didn’t use the MRIQC workflow?

That is not possible by design. MRIQC only works on **original** data. The only acceptable preprocessing step is defacing (i.e. removing facial features from anatomical scans) for HIPAA/GDPR requirements.

> 2) Can MRIQC generate qualitative reports for other MRI contrasts (besides anatomical and functional), such as diffusion MRI, QSM MRI?

It can't. We would be very happy to incorporate such extensions, should someone contribute them.

> 3) Where can I get an test example of MRIQC

If you want data to run MRIQC on your own, https://openneuro.org has lots of datasets in the right BIDS format. If you want to see examples of reports generated by MRIQC -> https://mriqc.s3.amazonaws.com/index.html#openfmri/
