### ISSUE TITLE
[--hmc-afni] [--hmc-fsl]

### ISSUE THREAD

**Issue by gaelleroux** [poldracklab/mriqc#887]
Hi,

I use v0.16.0 and it fails when I use the head motion correction --hmc (afni or fsl). If I run it without this option, the process ends well and I was able to use --hmc-fsl and afni on the same dataset using v0.15.2.

Anyone clue maybe?
Best,
Gaëlle

**Comment by effigies** [comment]
Support for FSL MCFLIRT was removed in 0.16.0. HMC is now done with AFNI 3dVolReg.

**Comment by oesteban** [comment]
Yup, reasons for this move:
1. Try not to use FSL whenever possible, in favor of other packages without commercial restrictions
2. FSL MCFLIRT needs to manipulate the orientation headers, e.g., when running rodents, because it expects human-sized brains.
3. We have experienced biased FD series for FSL MCFLIRT, with apparent drifts increasing with time. This effect does not seem to be so notorious with 3dVolReg.

Given the design principles of MRIQC (simplicity, speed over accuracy, reliability) it was a really easy decision to be made.

**Comment by gaelleroux** [comment]
Thank you very much for your replies.
Best, Gaëlle
